### ISSUE TITLE
Reset pwd and Login

### ISSUE THREAD

**Issue by wvdvegt** [gorco/gf#37]
If you press the Forgot your password? link at http://145.20.132.23:3000/api/proxy/afront and then press the login button at the top right you get an error on a url http://145.20.132.23:3000/api/proxy/afront/login/login

```
Error: Not Found
    at /app/app/app.js:38:15
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at /app/node_modules/express/lib/router/index.js:618:15
    at next (/app/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/app/node_modules/express/lib/router/index.js:176:3)
    at router (/app/node_modules/express/lib/router/index.js:46:12)
```

**Comment by wvdvegt** [comment]
The Forgot your password? also fails on this page (the URL changes but the page stays the same).

At http://145.20.132.23:3000/login the same link works.
